---
title: "Iterations and List Cols"
author: "Shivalika Chavan"
date: "2025-10-28"
output: github_document
---

```{r collapse=TRUE}
library(tidyverse)
library(rvest)
```

```{r}
l = 
  list(
    vec_numeric = 1:23,
    vec_char = c("Shivalika"),
    mat = matrix(1:8, nrow = 2, ncol = 4),
    summary = summary(rnorm(1000), mean = 4)
  )

l[[1]]
l[["vec_numeric"]]
l$mat
```


```{r}
list_normals = 
  list(
    a = rnorm(30, mean = 3, sd = 1),
    b = rnorm(30, mean = 30, sd = 0.5),
    c = rnorm(30, mean = -4, sd = 3),
    d = rnorm(30, mean = 12, sd = 4)
  )
```

Can either copy and paste the function
```{r}
source("source/mean_and_sd.R")

mean_and_sd(list_normals[[1]])
mean_and_sd(list_normals[[2]])
mean_and_sd(list_normals[[3]])
mean_and_sd(list_normals[[4]])
```

Use a loop to iterate
```{r}
output = vector("list", length = 4) #defining an empty list

for (i in 1:4){
  
  output[[i]] = mean_and_sd(list_normals[[i]])
  
}

```

or...
```{r}
output = map(list_normals, mean_and_sd)
# can use this for any function
output = map(list_normals, median)
```


Map variants
```{r}

map_dfr(list_normals, mean_and_sd, .id = "sample")
map_dbl(list_normals, median)
```

list cols in data frame
```{r}
list_col_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    sample = list_normals
  )

pull(list_col_df, sample)
pull(list_col_df, name)
```


```{r}
list_col_df = 
  list_col_df  |> 
  mutate(
    summary = map(sample, mean_and_sd)
  )

pull(list_col_df, summary)
```

```{r}
list_col_df |> 
  select(-sample) |> 
  unnest(summary)
```


Revisit NSDUH
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

nsduh_table <- function(html, table_num) {
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent)) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
  table
  
}

nsduh_results = 
  bind_rows(
    nsduh_table(nsduh_html, table_num = 1),
    nsduh_table(nsduh_html, table_num = 4),
    nsduh_table(nsduh_html, table_num = 5)
  )
```

Trying the above with a for loop
```{r}

output = vector("list", length = 3)
for (i in 1:3){
  output[[i]] = nsduh_table(html = nsduh_html, i)
}

```

same thing with map
```{r}
output = map(1:3, nsduh_table, html = nsduh_html)
```


everything in a data frame
```{r}
nsduh_df =
  tibble(
    name = c("marj year", "marj month", 'marj first'),
    number = 1:3
  ) |> 
  mutate(
    table = map(number, nsduh_table, html = nsduh_html)
  ) |> 
  unnest(table)
```


```{r}
library(p8105.datasets)
data("weather_df")
```

```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

Doing regression
```{r}
weather_df |> 
  filter(name == "CentralPark_NY") |> 
  lm(tmax ~ tmin, data = _)

weather_df |> 
  filter(name == "Molokai_HI") |> 
  lm(tmax ~ tmin, data = _)

weather_df |> 
  filter(name == "Waterhole_WA") |> 
  lm(tmax ~ tmin, data = _)
```

iterate
```{r}
weather_nest = 
  weather_df |> 
  nest(data = date:tmin)
```

```{r}

lm(tmax ~ tmin, data = pull(weather_nest, data)[[1]])
lm(tmax ~ tmin, data = pull(weather_nest, data)[[2]])
lm(tmax ~ tmin, data = pull(weather_nest, data)[[3]])
```


```{r}

weather_lm = function(df){
  lm(tmax ~ tmin, data = df)
}
```

