---
title: "Simulations"
author: "Shivalika Chavan"
date: "2025-10-30"
output: github_document
---

```{r collapse=TRUE}
library(tidyverse)
source("source/sim_mean_sd.R")

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d


set.seed(1)
```

```{r}
sim_mean_sd(n_subj = 40)
```

Running a simulation. "Verifying" CLT using a for loop

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  
  output[[i]] = sim_mean_sd(n_subj = 30)
  
}

sim_results = bind_rows(output)

sim_results |> 
  ggplot(aes(x = mu_hat)) +
  geom_histogram()
```

Using map statement

```{r}
sim_results_df = 
  expand_grid(
    sample_size = 30,
    iter = 1:100
  ) |> 
  mutate(
    results = map(sample_size, sim_mean_sd)
  ) |> 
  unnest(results)

sim_results_df |> 
  ggplot(aes(x = mu_hat)) + 
  geom_density()
```

```{r}
sim_results_df = 
  expand_grid(
    sample_size = c(30, 60, 90, 120),
    iter = 1:1000
  ) |> 
  mutate(
    results = map(sample_size, sim_mean_sd)
  ) |> 
  unnest(results)
```


Looking at the results

```{r}
sim_results_df |> 
  mutate(
    samp = str_c("n = ", sample_size),
    samp = fct_inorder(samp)) |>
  ggplot(aes(x = sample_size, y = mu_hat, fill = samp)) + 
  geom_violin()
```


Summarizing

```{r}
sim_results_df |> 
  group_by(sample_size) |> 
  summarize(
    empirical_mean = mean(mu_hat),
    empirical_se = sd(mu_hat)
  )
```

## Simple Linear Regression

```{r}
sim_df = 
  tibble(
    x = rnorm(30, mean = 1, sd = 1),
    y = 2 + 3*x + rnorm(30, mean = 0, sd = 1)
  )

sim_df |> 
  ggplot(aes(x = x, y = y)) +
  geom_point()


slr_fit = lm(y ~ x, data = sim_df)

coef(slr_fit)
```


Turn this into a function
```{r}
sim_regression = function(n_subj, beta_0 = 2, beta_1 = 3){
  
  sim_df = 
  tibble(
    x = rnorm(n_subj, mean = 1, sd = 1),
    y = beta_0 + beta_1*x + rnorm(n_subj, mean = 0, sd = 1)
  )
  
  slr_fit = lm(y ~ x, data = sim_df)
  
  tibble(
    beta_0_hat = coef(slr_fit)[1],
    beta_1_hat = coef(slr_fit)[2]
  )
}
```


```{r}
sim_regression(n_subj = 30)
```

simulating with a for loop
```{r}
output = vector("list", length = 500)
for (i in 1:500){
  output[[i]] = sim_regression(n_subj = 30)
}
output |> bind_rows()
```


```{r}
slr_sim_results_df = 
  expand_grid(
    sample_size = 30,
    iter = 1:500
  ) |> 
  mutate(
    results = map(sample_size, sim_regression)
  ) |> 
  unnest(results)

slr_sim_results_df |> 
  ggplot(aes(x = beta_0_hat, y = beta_1_hat)) + 
  geom_point()
```


## Last example - Birthday problem
```{r}
birthdays = sample(1:365, 50, replace = TRUE)

repeated_bday = length(unique(birthdays)) < 50

repeated_bday
```

```{r}
bday_sim = function(n_room){
  
  birthdays = sample(1:365, n_room, replace = TRUE)

  repeated_bday = length(unique(birthdays)) < n_room
  
  repeated_bday
}
```



```{r}
bday_sim_results = 
  expand_grid(
    bdays = 1:60,
    iter = 1:2500
  ) |> 
  mutate(
    results = map_lgl(bdays, bday_sim)
  ) |> 
  group_by(bdays) |> 
  summarize(
    prob = mean(results)
  ) 

bday_sim_results|> 
  ggplot(aes(x = bdays, y = prob)) +
  geom_point() + geom_line()
```

