---
title: "Writing Functions"
author: "Shivalika Chavan"
date: "2025-10-23"
output: github_document
---

```{r collapse=TRUE}
library(tidyverse)
library(rvest)
library(readxl)

set.seed(1)
```

Z scores
```{r collapse=TRUE}
x_vec = rnorm(20, mean = 10, sd = 3.5)

(x_vec - mean(x_vec)) / sd(x_vec)

```

Write a function to compute z score
```{r collapse=TRUE}
z_scores = function(x){
  if(!is.numeric(x)){
    stop("The input of x should be numeric")
  }
  if(length(x)<5){
    stop("Only compute z scores when input has 5 or more numbers")
  }
  z = (x - mean(x)) / sd(x)
  z
}
```

Trying function
```{r collapse=TRUE}
z_scores(x = x_vec)

num_vec = rnorm(123, mean = 14, sd = 0.4)
z_scores(x = num_vec)
```

Breaking the function
```{r error=TRUE, collapse=TRUE}
z_scores(3)
z_scores("My name is Shivalika")
```

Computing some stuff
Return mean and sd of a numeric vector
```{r collapse=TRUE}
mean_and_sd = function(x){
  
  if(!is.numeric(x)){
    stop("The input of x should be numeric")
  }
  
  if(length(x) < 5){
    stop("Only compute z scores when input has 5 or more numbers")
  }
  
  mean_x = mean(x, na.rm = TRUE)
  sd_x = sd(x, na.rm = TRUE)
  
  # c(mean_x, sd_x)
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}

mean_and_sd(x_vec)
```

Making up data (simulations)
```{r}
sim_df = 
  tibble(
    x = rnorm(n = 30, mean = 3, sd = 2)
  )


sim_df |> 
  summarize(
    mu_hat = mean(x),
    sigma_hat = sd(x)
  )
```

```{r}
sim_mean_sd = function(n_subj = 30, mu = 3, sigma = 2){
  sim_df = 
  tibble(
    x = rnorm(n = n_subj, mean = mu, sd = sigma)
  )
  sim_df |> 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
      )
}
```

```{r}
sim_mean_sd(mu = 48, 50)
```

Import LoTR data
```{r}
fellowship_ring = 
  read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |> 
  mutate(
    movie = "Fellowship of the Ring"
  )

two_towers = 
  read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |> 
  mutate(
    movie = "Two Towers"
  )

return_of_the_king = 
  read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |> 
  mutate(
    movie = "Return of the King"
  )

lotr_df = bind_rows(fellowship_ring, two_towers, return_of_the_king)
```

Same thing but a function
```{r}
import_lotr = function(filepath = "./data/LotR_Words.xlsx", xlsx_range, title){
  movie_df = 
  read_excel(filepath, range = xlsx_range) |> 
  mutate(
    movie = title
  )
}
fellowship_ring = import_lotr(xlsx_range = "B3:D6", title = "Fellowship of the Ring")
two_towers = import_lotr(xlsx_range = "F3:H6", title = "Two Towers")
return_of_the_king = import_lotr(xlsx_range = "J3:L6", title = "Return of the King")

lotr_df = bind_rows(fellowship_ring, two_towers, return_of_the_king)
```

Last example
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)
```


```{r}
data_marj = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1) |> 
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |>
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```


```{r}
nsduh_table <- function(html, table_num, table_name) {
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent),
      name = table_name) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
  table
  
}

nsduh_results = 
  bind_rows(
    nsduh_table(nsduh_html, table_num = 1, "marj_one_year"),
    nsduh_table(nsduh_html, table_num = 4, "cocaine_one_year"),
    nsduh_table(nsduh_html, table_num = 5, "heroin_one_year")
  )
```

